# Generated by Django 4.2.1 on 2023-06-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Genre", "verbose_name_plural": "Genres"},
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(
                default="authoor", max_length=255, verbose_name="Author"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="The image of book",
                upload_to="",
                verbose_name="Book image",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                default="Authoor", max_length=255, verbose_name="Genre"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="number_of_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="size",
            field=models.CharField(
                default="authoor", max_length=255, verbose_name="Size"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Book"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Price"
            ),
        ),
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
    ]
