# Generated by Django 4.2.1 on 2023-06-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_book_options_alter_book_number_of_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="size",
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="book",
            name="dimensions",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Dimensions"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(blank=True, max_length=255, verbose_name="Language"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=255, verbose_name="Genre"),
        ),
        migrations.AlterField(
            model_name="book",
            name="number_of_pages",
            field=models.CharField(blank=True, verbose_name="Number of pages"),
        ),
    ]
