# Generated by Django 4.2.1 on 2023-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_book_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "book"},
        ),
        migrations.RemoveField(
            model_name="book",
            name="name",
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.CharField(blank=True, verbose_name="Publication date"),
        ),
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default="1", max_length=255, verbose_name="Title"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255, verbose_name="Authors"),
        ),
    ]
