# Generated by Django 4.2.1 on 2023-06-17 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_book_options_remove_book_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.AlterModelTable(
            name="book",
            table=None,
        ),
    ]
