# Generated by Django 4.2.1 on 2023-06-26 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_alter_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=3, null=True
            ),
        ),
        migrations.CreateModel(
            name="UserBookRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.BooleanField(default=False)),
                ("add_to_list", models.BooleanField(default=False)),
                (
                    "rate",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below average"),
                            (3, "Average"),
                            (4, "Above average"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
