# Generated by Django 4.2.1 on 2023-07-15 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0010_alter_userbookrelation_add_to_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="customers",
            field=models.ManyToManyField(
                related_name="books",
                through="products.UserBookRelation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
