# Generated by Django 4.2.1 on 2023-07-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0011_book_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
