# Generated by Django 4.2.1 on 2023-07-27 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_book_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="creator",
        ),
    ]
