# Generated by Django 4.2.1 on 2023-10-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="like",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="rate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below average"),
                    (3, "Average"),
                    (4, "Above average"),
                    (5, "Excellent"),
                ],
                default=False,
                null=True,
            ),
        ),
    ]
