# Generated by Django 4.2.1 on 2023-10-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_remove_book_language_alter_userbookrelation_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=3, verbose_name="In stock"),
            preserve_default=False,
        ),
    ]
