# Generated by Django 4.2.1 on 2024-02-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="The image of book",
                upload_to="assets/products",
                verbose_name="Cover",
            ),
        ),
    ]
