# Generated by Django 4.2.1 on 2024-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_alter_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="quantity",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="In stock"),
        ),
    ]
